name: resource_repository_hive
description: Hive storage for the resource_repository package.
version: 0.0.2
homepage: https://github.com/NaikSoftware/resource_repository_hive

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  resource_repository_storage: ^0.0.2+1
  rxdart: ^0.27.5
  synchronized: ^3.0.0+3
  worker_manager: ^4.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

